CANCIONES_POPULARES = [
    {"titulo": "Blinding Lights", "artista": "The Weeknd", "album": "After Hours"},
    {"titulo": "Shape of You", "artista": "Ed Sheeran", "album": "Divide"},
    {"titulo": "Bohemian Rhapsody", "artista": "Queen", "album": "A Night at the Opera"},
    {"titulo": "Levitating", "artista": "Dua Lipa", "album": "Future Nostalgia"},
    {"titulo": "Stay", "artista": "The Kid LAROI & Justin Bieber", "album": "F*CK LOVE 3"},
    {"titulo": "Peaches", "artista": "Justin Bieber", "album": "Justice"},
    {"titulo": "Good 4 U", "artista": "Olivia Rodrigo", "album": "SOUR"},
    {"titulo": "drivers license", "artista": "Olivia Rodrigo", "album": "SOUR"},
    {"titulo": "Montero", "artista": "Lil Nas X", "album": "Montero"},
    {"titulo": "Industry Baby", "artista": "Lil Nas X", "album": "Montero"},
    {"titulo": "Save Your Tears", "artista": "The Weeknd", "album": "After Hours"},
    {"titulo": "Dynamite", "artista": "BTS", "album": "Dynamite"},
    {"titulo": "Butter", "artista": "BTS", "album": "Butter"},
    {"titulo": "Permission to Dance", "artista": "BTS", "album": "Permission to Dance"},
    {"titulo": "As It Was", "artista": "Harry Styles", "album": "Harry's House"},
    {"titulo": "Watermelon Sugar", "artista": "Harry Styles", "album": "Fine Line"},
    {"titulo": "Anti-Hero", "artista": "Taylor Swift", "album": "Midnights"},
    {"titulo": "Shake It Off", "artista": "Taylor Swift", "album": "1989"},
    {"titulo": "Blank Space", "artista": "Taylor Swift", "album": "1989"},
    {"titulo": "Bad Blood", "artista": "Taylor Swift", "album": "1989"},
    {"titulo": "Cruel Summer", "artista": "Taylor Swift", "album": "Lover"},
    {"titulo": "Bad Guy", "artista": "Billie Eilish", "album": "When We All Fall Asleep"},
    {"titulo": "Happier Than Ever", "artista": "Billie Eilish", "album": "Happier Than Ever"},
    {"titulo": "Flowers", "artista": "Miley Cyrus", "album": "Endless Summer Vacation"},
    {"titulo": "Unholy", "artista": "Sam Smith & Kim Petras", "album": "Gloria"},
    {"titulo": "Heat Waves", "artista": "Glass Animals", "album": "Dreamland"},
    {"titulo": "Easy On Me", "artista": "Adele", "album": "30"},
    {"titulo": "Hello", "artista": "Adele", "album": "25"},
    {"titulo": "Rolling in the Deep", "artista": "Adele", "album": "21"},
    {"titulo": "Someone Like You", "artista": "Adele", "album": "21"},
    {"titulo": "Uptown Funk", "artista": "Mark Ronson ft. Bruno Mars", "album": "Uptown Special"},
    {"titulo": "That's What I Like", "artista": "Bruno Mars", "album": "24K Magic"},
    {"titulo": "Locked Out of Heaven", "artista": "Bruno Mars", "album": "Unorthodox Jukebox"},
    {"titulo": "Despacito", "artista": "Luis Fonsi ft. Daddy Yankee", "album": "Vida"},
    {"titulo": "Con Calma", "artista": "Daddy Yankee", "album": "Con Calma"},
    {"titulo": "Gasolina", "artista": "Daddy Yankee", "album": "Barrio Fino"},
    {"titulo": "Tusa", "artista": "Karol G & Nicki Minaj", "album": "Tusa"},
    {"titulo": "Bichota", "artista": "Karol G", "album": "KG0516"},
    {"titulo": "MAMIII", "artista": "Becky G & Karol G", "album": "MAMIII"},
    {"titulo": "Hawai", "artista": "Maluma", "album": "Papi Juancho"},
    {"titulo": "Dakiti", "artista": "Bad Bunny & Jhay Cortez", "album": "El Ultimo Tour Del Mundo"},
    {"titulo": "Yonaguni", "artista": "Bad Bunny", "album": "El Ultimo Tour Del Mundo"},
    {"titulo": "Me Porto Bonito", "artista": "Bad Bunny & Chencho Corleone", "album": "Un Verano Sin Ti"},
    {"titulo": "Noche de Anoche", "artista": "Bad Bunny & Rosalia", "album": "El Ultimo Tour Del Mundo"},
    {"titulo": "Motomami", "artista": "Rosalia", "album": "Motomami"},
    {"titulo": "Shakira: Bzrp Music Sessions 53", "artista": "Bizarrap & Shakira", "album": "Bzrp Music Sessions"},
    {"titulo": "Waka Waka", "artista": "Shakira", "album": "She Wolf"},
    {"titulo": "Hips Don't Lie", "artista": "Shakira ft. Wyclef Jean", "album": "Oral Fixation"},
    {"titulo": "Thriller", "artista": "Michael Jackson", "album": "Thriller"},
    {"titulo": "Billie Jean", "artista": "Michael Jackson", "album": "Thriller"},
    {"titulo": "Beat It", "artista": "Michael Jackson", "album": "Thriller"},
    {"titulo": "Smells Like Teen Spirit", "artista": "Nirvana", "album": "Nevermind"},
    {"titulo": "Hotel California", "artista": "Eagles", "album": "Hotel California"},
    {"titulo": "Stairway to Heaven", "artista": "Led Zeppelin", "album": "Led Zeppelin IV"},
    {"titulo": "Sweet Child O Mine", "artista": "Guns N Roses", "album": "Appetite for Destruction"},
    {"titulo": "November Rain", "artista": "Guns N Roses", "album": "Use Your Illusion I"},
    {"titulo": "Lose Yourself", "artista": "Eminem", "album": "8 Mile Soundtrack"},
    {"titulo": "Without Me", "artista": "Eminem", "album": "The Eminem Show"},
    {"titulo": "Stan", "artista": "Eminem", "album": "The Marshall Mathers LP"},
    {"titulo": "God's Plan", "artista": "Drake", "album": "Scorpion"},
    {"titulo": "One Dance", "artista": "Drake", "album": "Views"},
    {"titulo": "Hotline Bling", "artista": "Drake", "album": "Views"},
    {"titulo": "SICKO MODE", "artista": "Travis Scott", "album": "Astroworld"},
    {"titulo": "Rockstar", "artista": "Post Malone", "album": "Beerbongs & Bentleys"},
    {"titulo": "Sunflower", "artista": "Post Malone & Swae Lee", "album": "Spider-Man: Into the Spider-Verse"},
    {"titulo": "Circles", "artista": "Post Malone", "album": "Hollywood's Bleeding"},
    {"titulo": "Old Town Road", "artista": "Lil Nas X ft. Billy Ray Cyrus", "album": "7 EP"},
    {"titulo": "We Will Rock You", "artista": "Queen", "album": "News of the World"},
    {"titulo": "Don't Stop Me Now", "artista": "Queen", "album": "Jazz"},
    {"titulo": "Under Pressure", "artista": "Queen & David Bowie", "album": "Hot Space"},
    {"titulo": "Let It Be", "artista": "The Beatles", "album": "Let It Be"},
    {"titulo": "Hey Jude", "artista": "The Beatles", "album": "Hey Jude"},
    {"titulo": "Come Together", "artista": "The Beatles", "album": "Abbey Road"},
    {"titulo": "Yesterday", "artista": "The Beatles", "album": "Help!"},
    {"titulo": "Imagine", "artista": "John Lennon", "album": "Imagine"},
    {"titulo": "Superstition", "artista": "Stevie Wonder", "album": "Talking Book"},
    {"titulo": "Purple Rain", "artista": "Prince", "album": "Purple Rain"},
    {"titulo": "We dont talk anymore", "artista": "Charlie Puth", "album": "Nine Track Mind"},
    {"titulo": "Attention", "artista": "Charlie Puth", "album": "Voicenotes"},
    {"titulo": "See You Again", "artista": "Wiz Khalifa ft. Charlie Puth", "album": "Furious 7 Soundtrack"},
    {"titulo": "Perfect", "artista": "Ed Sheeran", "album": "Divide"},
    {"titulo": "Thinking Out Loud", "artista": "Ed Sheeran", "album": "X"},
    {"titulo": "Photograph", "artista": "Ed Sheeran", "album": "X"},
]